NAME = megaphone
CC = c++
FALGS = -Wall -Wextra -Werror -std=c++98

SRC = megaphone.cpp 
REMOVE = rm -rf

all: $(NAME)

$(NAME): $(SRC) 
	$(CC) $(FLAGS) -g $(SRC) -o $(NAME)

clean:
	$(REMOVE) $(NAME)

re: clean all